"""Add Review Model

Revision ID: bca322dce0ec
Revises: 7a6ee09cf107
Create Date: 2023-06-12 10:48:59.839103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca322dce0ec'
down_revision = '7a6ee09cf107'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
